### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-gitops-cp-mq#19]
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Duplicate module call
│ 
│   on module/provider.tf line 7:
│    7: module setup_clis {
│ 
│ A module call named "setup_clis" was already defined at
│ module/main.tf:28,1-18. Module calls must have unique names within a
│ module.
╵

**Comment by seansund** [comment]
@balasgit The provider.tf file is in the wrong place. You put it in the root directory and it needs to be in test/stages

**Comment by balasgit** [comment]
Fixed - its Typo mistakenly placed @seansund. thanks for catching up

**Comment by balasgit** [comment]
One pending error

More details - https://github.com/cloud-native-toolkit/terraform-gitops-cp-mq/actions/runs/3139296019/jobs/5099560405


 Error: Reference to undeclared module
│ 
│   on module/main.tf line 3, in locals:
│    3:   bin_dir       = module.setup_clis.bin_dir
│ 
│ No module call named "setup_clis" is declared in module.gitops_module.
╵
╷
│ Warning: Attribute Deprecated
│ 
│   with module.dev_cluster.module.setup_clis.random_string.uuid,
│   on .terraform/modules/dev_cluster.setup_clis/main.tf line 15, in resource "random_string" "uuid":
│   15:   number  = false
│ 
│ **NOTE**: This is deprecated, use `numeric` instead.
│ 
│ (and 2 more similar warnings elsewhere)
╵
